[package]
name = "mellon-book"
version = "0.1.0"
edition = "2021"

[dependencies]
ratatui = "0.29.0"
turann = { git = "https://github.com/masterned/turann.git", tag = "v1.0.0" }

[dependencies.uuid]
version = "1.13.1"
features = [
  "v4",
  "fast-rng",
  "macro-diagnostics",
]
